# Generated by Django 5.1.2 on 2025-09-22 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id_nodo', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('defectuoso', models.BooleanField(default=False)),
                ('modelo_gps', models.CharField(blank=True, max_length=100, null=True)),
                ('bateria', models.IntegerField(default=100)),
                ('codigo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('contador', models.IntegerField(blank=True, default=0, null=True)),
                ('id_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_nodo', to='nodos.nodo')),
            ],
        ),
    ]
