# Generated by Django 5.2 on 2025-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nodo', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lat', models.CharField()),
                ('lon', models.CharField()),
            ],
        ),
    ]
