# Generated by Django 5.1.2 on 2025-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
