# Generated by Django 5.1.2 on 2025-10-27 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_cuidador_cuit_alter_cuidador_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CUIG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuario.establecimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuario.rol'),
        ),
    ]
