# Generated by Django 5.1.2 on 2025-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_cuig_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='apellido_cuidador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='nombre_cuidador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='CUIG',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
