# Generated by Django 5.1.2 on 2025-09-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_cuidador_apellido_cuidador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='CUIT',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
