# Generated by Django 5.1.2 on 2025-11-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_solicitudunion_fecha_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudunion',
            name='rol_solicitado',
        ),
    ]
