# Generated by Django 5.1.2 on 2025-09-02 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodos', '__first__'),
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especie', models.CharField(max_length=50, unique=True)),
                ('id_raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especie_raza', to='animal.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('carabana', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('CUIG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_establecimiento', to='usuario.establecimiento')),
                ('id_cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_cuidador', to='usuario.cuidador')),
                ('id_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_nodo', to='nodos.nodo')),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_especie', to='animal.especie')),
                ('id_raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_raza', to='animal.raza')),
            ],
        ),
    ]
