# Generated by Django 5.1.2 on 2025-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='carabana',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
