# Generated by Django 5.1.2 on 2025-09-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_animal_carabana'),
        ('nodos', '0002_alter_nodo_defectuoso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_nodo', to='nodos.nodo', unique=True),
        ),
    ]
